### ISSUE TITLE
Specify asset path for plugin? 

### ISSUE THREAD

**Issue by jorySsense** [mario-jerkovic/flush-css-chunks-webpack-plugin#1]
Hi i just used your plugin, works amazing but i need to change the asset path, I have a free weekend so I can try to make a PR.

**Comment by mario-jerkovic** [comment]
Thank you for the feedback... Can't you just change the `publicPath` in you webpack config as this plugin is using it to generate the mapping and inject it in `window` object

**Comment by mario-jerkovic** [comment]
Or maybe we can add an additional `options` property to override the `publicPath` ... :) ?
