### ISSUE TITLE
Specify entry?

### ISSUE THREAD

**Issue by 8427003** [mario-jerkovic/flush-css-chunks-webpack-plugin#3]
can Specify entry?   my entry is mutil.   every entry injected,  that is bad

**Comment by mario-jerkovic** [comment]
Sorry for the late response...

Actually that is a good idea. I think we could and an additional property to specify in which entry would the CSS mapping be injected... Will do the initial implementation this weekend. Maybe if you have an idea for concrete implementation you could submit a PR 🍺
